name: Publish Jar and Docker Image

on:
  push:
    tags:
      - '*'   # Trigger nur bei Tag-Push (Release)

jobs:
  publish-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build and Deploy Jar to GitHub Packages
        working-directory: ./api
        run: mvn clean deploy

  publish-container:
    needs: publish-jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/discount-server:${{ github.ref_name }}
          docker build -t $IMAGE .
          docker push $IMAGE
